In [10]:
from __future__ import print_function

from osgeo import gdal

print("GDAL's version is : " + gdal.__version__)
print(gdal)

GDAL's version is : 3.6.4
<module 'osgeo.gdal' from '/usr/local/lib/python3.10/dist-packages/osgeo/gdal.py'>


In [13]:
dataset = gdal.Open('LC08_L2SP_114035_20240730_20240801_02_T1_SR_B2.TIF', gdal.GA_ReadOnly)

print(dataset)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7ebf3b230420> >


In [14]:
num_bands = dataset.RasterCount
print('Number of bands in image: {n}\n'.format(n=num_bands))

rows = dataset.RasterYSize
cols = dataset.RasterXSize
print('Image seize is: {r} rows x {c} columns\n'.format(r=rows, c=cols))

desc = dataset.GetDescription()
metadata = dataset.GetMetadata()

print('Raster description : {desc}'.format(desc = desc))
print('Raster metadata:')
print(metadata)
print('\n')

driver = dataset.GetDriver()
print('Raster driver : {d}\n'.format(d=driver.ShortName))

Number of bands in image: 1

Image seize is: 7821 rows x 7681 columns

Raster description : LC08_L2SP_114035_20240730_20240801_02_T1_SR_B2.TIF
Raster metadata:
{'AREA_OR_POINT': 'Point'}


Raster driver : GTiff



In [17]:
blue = dataset.GetRasterBand(1)

print(blue)

<osgeo.gdal.Band; proxy of <Swig Object of type 'GDALRasterBandShadow *' at 0x7ebef3f21dd0> >


In [22]:
datatype = blue.DataType
print('Band datatype : {dt}'.format(dt=blue.DataType))

datatype_name = gdal.GetDataTypeName(blue.DataType)
print('Band datatype : {dt}'.format(dt=datatype_name))

bytes = gdal.GetDataTypeSize(blue.DataType)
print('Band datatype size : {b} bytes\n'.format(b=bytes))

band_max, band_min, band_mean, band_stddev = blue.GetStatistics(0,1)
print('Band range : {minimum} - {maximum}'.format(maximum=band_max, minimum=band_min))
print('Band mean, stddev : {m}, {s}\n'.format(m=band_mean, s=band_stddev))

bule_data = blue.ReadAsArray()

Band datatype : 2
Band datatype : UInt16
Band datatype size : 16 bytes

Band range : 57776.0 - 1.0
Band mean, stddev : 13357.309216986, 10519.044675774



In [23]:
import numpy
print(numpy.__version__)

import numpy as np
print(np.__version__)

image = np.zeros((dataset.RasterYSize, dataset.RasterXSize, dataset.RasterCount))

for b in range(dataset.RasterCount):
    band = dataset.GetRasterBand(b + 1)

    image[:, :, b] = band.ReadAsArray()

print(image)
print(image.dtype)

1.26.4
1.26.4
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]]
float64


IndexError: index 2 is out of bounds for axis 2 with size 1